name = "HnswAnn"
uuid = "dff2f42d-5506-450f-a8d7-e8287f476a07"
author = ["Jean-Pierre Both <jeanpierre.both@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"
Match = "1.1"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]